export interface WorldCountry {
  code: string;       // Dial code e.g. '+966'
  country: string;    // ISO 2-letter code e.g. 'SA'
  flag: string;       // Emoji flag e.g. '🇸🇦'
  name: string;       // English name
  nameAr: string;     // Arabic name
  placeholder: string;// Example phone format
}

export const WORLD_COUNTRIES: WorldCountry[] = [
  // --- Priority Regional Countries (Arab & Gulf Region) ---
  { code: '+966', country: 'SA', flag: '🇸🇦', name: 'Saudi Arabia', nameAr: 'السعودية', placeholder: '50 123 4567' },
  { code: '+20', country: 'EG', flag: '🇪🇬', name: 'Egypt', nameAr: 'مصر', placeholder: '10 1234 5678' },
  { code: '+218', country: 'LY', flag: '🇱🇾', name: 'Libya', nameAr: 'ليبيا', placeholder: '91 123 4567' },
  { code: '+971', country: 'AE', flag: '🇦🇪', name: 'United Arab Emirates', nameAr: 'الإمارات العربية المتحدة', placeholder: '50 123 4567' },
  { code: '+974', country: 'QA', flag: '🇶🇦', name: 'Qatar', nameAr: 'قطر', placeholder: '33 123 456' },
  { code: '+965', country: 'KW', flag: '🇰🇼', name: 'Kuwait', nameAr: 'الكويت', placeholder: '91 234 567' },
  { code: '+973', country: 'BH', flag: '🇧🇭', name: 'Bahrain', nameAr: 'البحرين', placeholder: '39 123 456' },
  { code: '+968', country: 'OM', flag: '🇴🇲', name: 'Oman', nameAr: 'عُمان', placeholder: '91 234 567' },
  { code: '+962', country: 'JO', flag: '🇯🇴', name: 'Jordan', nameAr: 'الأردن', placeholder: '7 9123 4567' },
  { code: '+961', country: 'LB', flag: '🇱🇧', name: 'Lebanon', nameAr: 'لبنان', placeholder: '70 123 456' },
  { code: '+964', country: 'IQ', flag: '🇮🇶', name: 'Iraq', nameAr: 'العراق', placeholder: '770 123 4567' },
  { code: '+970', country: 'PS', flag: '🇵🇸', name: 'Palestine', nameAr: 'فلسطين', placeholder: '59 912 3456' },
  { code: '+249', country: 'SD', flag: '🇸🇩', name: 'Sudan', nameAr: 'السودان', placeholder: '91 123 4567' },
  { code: '+212', country: 'MA', flag: '🇲🇦', name: 'Morocco', nameAr: 'المغرب', placeholder: '61 234 5678' },
  { code: '+216', country: 'TN', flag: '🇹🇳', name: 'Tunisia', nameAr: 'تونس', placeholder: '20 123 456' },
  { code: '+213', country: 'DZ', flag: '🇩🇿', name: 'Algeria', nameAr: 'الجزائر', placeholder: '55 12 34 567' },
  { code: '+967', country: 'YE', flag: '🇾🇪', name: 'Yemen', nameAr: 'اليمن', placeholder: '77 123 4567' },
  { code: '+963', country: 'SY', flag: '🇸🇾', name: 'Syria', nameAr: 'سوريا', placeholder: '93 123 4567' },
  { code: '+90', country: 'TR', flag: '🇹🇷', name: 'Turkey', nameAr: 'تركيا', placeholder: '512 345 6789' },
  { code: '+1', country: 'US', flag: '🇺🇸', name: 'United States', nameAr: 'أمريكا (الولايات المتحدة)', placeholder: '202 555 0123' },
  { code: '+44', country: 'GB', flag: '🇬🇧', name: 'United Kingdom', nameAr: 'بريطانيا (المملكة المتحدة)', placeholder: '7911 123456' },

  // --- Full Worldwide List (Alphabetical) ---
  { code: '+93', country: 'AF', flag: '🇦🇫', name: 'Afghanistan', nameAr: 'أفغانستان', placeholder: '70 123 4567' },
  { code: '+355', country: 'AL', flag: '🇦🇱', name: 'Albania', nameAr: 'ألبانيا', placeholder: '67 123 4567' },
  { code: '+376', country: 'AD', flag: '🇦🇩', name: 'Andorra', nameAr: 'أندورا', placeholder: '312 345' },
  { code: '+244', country: 'AO', flag: '🇦🇴', name: 'Angola', nameAr: 'أنغولا', placeholder: '912 345 678' },
  { code: '+54', country: 'AR', flag: '🇦🇷', name: 'Argentina', nameAr: 'الأرجنتين', placeholder: '11 1234 5678' },
  { code: '+374', country: 'AM', flag: '🇦🇲', name: 'Armenia', nameAr: 'أرمينيا', placeholder: '10 123456' },
  { code: '+61', country: 'AU', flag: '🇦🇺', name: 'Australia', nameAr: 'أستراليا', placeholder: '412 345 678' },
  { code: '+43', country: 'AT', flag: '🇦🇹', name: 'Austria', nameAr: 'النمسا', placeholder: '644 1234567' },
  { code: '+994', country: 'AZ', flag: '🇦🇿', name: 'Azerbaijan', nameAr: 'أذربيجان', placeholder: '50 123 45 67' },
  { code: '+880', country: 'BD', flag: '🇧🇩', name: 'Bangladesh', nameAr: 'بنغلاديش', placeholder: '1712 345678' },
  { code: '+375', country: 'BY', flag: '🇧🇾', name: 'Belarus', nameAr: 'بيلاروسيا', placeholder: '29 123 4567' },
  { code: '+32', country: 'BE', flag: '🇧🇪', name: 'Belgium', nameAr: 'بلجيكا', placeholder: '412 34 56 78' },
  { code: '+591', country: 'BO', flag: '🇧🇴', name: 'Bolivia', nameAr: 'بوليفيا', placeholder: '71234567' },
  { code: '+387', country: 'BA', flag: '🇧🇦', name: 'Bosnia & Herzegovina', nameAr: 'البوسنة والهرسك', placeholder: '61 123 456' },
  { code: '+55', country: 'BR', flag: '🇧🇷', name: 'Brazil', nameAr: 'البرازيل', placeholder: '11 91234 5678' },
  { code: '+359', country: 'BG', flag: '🇧🇬', name: 'Bulgaria', nameAr: 'بلغاريا', placeholder: '87 123 4567' },
  { code: '+1', country: 'CA', flag: '🇨🇦', name: 'Canada', nameAr: 'كندا', placeholder: '416 555 0123' },
  { code: '+56', country: 'CL', flag: '🇨🇱', name: 'Chile', nameAr: 'تشيلي', placeholder: '9 1234 5678' },
  { code: '+86', country: 'CN', flag: '🇨🇳', name: 'China', nameAr: 'الصين', placeholder: '139 1234 5678' },
  { code: '+57', country: 'CO', flag: '🇨🇴', name: 'Colombia', nameAr: 'كولومبيا', placeholder: '300 1234567' },
  { code: '+385', country: 'HR', flag: '🇭🇷', name: 'Croatia', nameAr: 'كرواتيا', placeholder: '91 123 4567' },
  { code: '+53', country: 'CU', flag: '🇨🇺', name: 'Cuba', nameAr: 'كوبا', placeholder: '5 1234567' },
  { code: '+357', country: 'CY', flag: '🇨🇾', name: 'Cyprus', nameAr: 'قبرص', placeholder: '96 123456' },
  { code: '+420', country: 'CZ', flag: '🇨🇿', name: 'Czech Republic', nameAr: 'التشيك', placeholder: '601 123 456' },
  { code: '+45', country: 'DK', flag: '🇩🇰', name: 'Denmark', nameAr: 'الدنمارك', placeholder: '32 12 34 56' },
  { code: '+253', country: 'DJ', flag: '🇩🇯', name: 'Djibouti', nameAr: 'جيبوتي', placeholder: '77 12 34 56' },
  { code: '+593', country: 'EC', flag: '🇪🇨', name: 'Ecuador', nameAr: 'الإكوادور', placeholder: '99 123 4567' },
  { code: '+372', country: 'EE', flag: '🇪🇪', name: 'Estonia', nameAr: 'إستونيا', placeholder: '5123 4567' },
  { code: '+251', country: 'ET', flag: '🇪🇹', name: 'Ethiopia', nameAr: 'إثيوبيا', placeholder: '91 123 4567' },
  { code: '+358', country: 'FI', flag: '🇫🇮', name: 'Finland', nameAr: 'فنلندا', placeholder: '45 1234567' },
  { code: '+33', country: 'FR', flag: '🇫🇷', name: 'France', nameAr: 'فرنسا', placeholder: '6 12 34 56 78' },
  { code: '+995', country: 'GE', flag: '🇬🇪', name: 'Georgia', nameAr: 'جورجيا', placeholder: '555 12 34 56' },
  { code: '+49', country: 'DE', flag: '🇩🇪', name: 'Germany', nameAr: 'ألمانيا', placeholder: '151 12345678' },
  { code: '+233', country: 'GH', flag: '🇬🇭', name: 'Ghana', nameAr: 'غانا', placeholder: '24 123 4567' },
  { code: '+30', country: 'GR', flag: '🇬🇷', name: 'Greece', nameAr: 'اليونان', placeholder: '691 234 5678' },
  { code: '+852', country: 'HK', flag: '🇭🇰', name: 'Hong Kong', nameAr: 'هونغ كونغ', placeholder: '9123 4567' },
  { code: '+36', country: 'HU', flag: '🇭🇺', name: 'Hungary', nameAr: 'المجر', placeholder: '20 123 4567' },
  { code: '+354', country: 'IS', flag: '🇮🇸', name: 'Iceland', nameAr: 'أيسلندا', placeholder: '612 3456' },
  { code: '+91', country: 'IN', flag: '🇮🇳', name: 'India', nameAr: 'الهند', placeholder: '98123 45678' },
  { code: '+62', country: 'ID', flag: '🇮🇩', name: 'Indonesia', nameAr: 'إندونيسيا', placeholder: '812 3456 789' },
  { code: '+98', country: 'IR', flag: '🇮🇷', name: 'Iran', nameAr: 'إيران', placeholder: '912 345 6789' },
  { code: '+353', country: 'IE', flag: '🇮🇪', name: 'Ireland', nameAr: 'أيرلندا', placeholder: '83 123 4567' },
  { code: '+39', country: 'IT', flag: '🇮🇹', name: 'Italy', nameAr: 'إيطاليا', placeholder: '312 345 6789' },
  { code: '+81', country: 'JP', flag: '🇯🇵', name: 'Japan', nameAr: 'اليابان', placeholder: '90 1234 5678' },
  { code: '+7', country: 'KZ', flag: '🇰🇿', name: 'Kazakhstan', nameAr: 'كازاخستان', placeholder: '701 123 4567' },
  { code: '+254', country: 'KE', flag: '🇰🇪', name: 'Kenya', nameAr: 'كينيا', placeholder: '712 345678' },
  { code: '+82', country: 'KR', flag: '🇰🇷', name: 'South Korea', nameAr: 'كوريا الجنوبية', placeholder: '10 1234 5678' },
  { code: '+996', country: 'KG', flag: '🇰🇬', name: 'Kyrgyzstan', nameAr: 'قيرغيزستان', placeholder: '700 123 456' },
  { code: '+371', country: 'LV', flag: '🇱🇻', name: 'Latvia', nameAr: 'لاتفيا', placeholder: '21 234 567' },
  { code: '+370', country: 'LT', flag: '🇱🇹', name: 'Lithuania', nameAr: 'ليتوانيا', placeholder: '612 34567' },
  { code: '+352', country: 'LU', flag: '🇱🇺', name: 'Luxembourg', nameAr: 'لوكسمبورغ', placeholder: '621 123 456' },
  { code: '+60', country: 'MY', flag: '🇲🇾', name: 'Malaysia', nameAr: 'ماليزيا', placeholder: '12 345 6789' },
  { code: '+960', country: 'MV', flag: '🇲🇻', name: 'Maldives', nameAr: 'جزر المالديف', placeholder: '712 3456' },
  { code: '+222', country: 'MR', flag: '🇲🇷', name: 'Mauritania', nameAr: 'موريتانيا', placeholder: '45 12 34 56' },
  { code: '+52', country: 'MX', flag: '🇲🇽', name: 'Mexico', nameAr: 'المكسيك', placeholder: '55 1234 5678' },
  { code: '+31', country: 'NL', flag: '🇳🇱', name: 'Netherlands', nameAr: 'هولندا', placeholder: '6 12345678' },
  { code: '+64', country: 'NZ', flag: '🇳🇿', name: 'New Zealand', nameAr: 'نيوزيلندا', placeholder: '21 123 4567' },
  { code: '+234', country: 'NG', flag: '🇳🇬', name: 'Nigeria', nameAr: 'نيجيريا', placeholder: '802 123 4567' },
  { code: '+47', country: 'NO', flag: '🇳🇴', name: 'Norway', nameAr: 'النرويج', placeholder: '412 34 567' },
  { code: '+92', country: 'PK', flag: '🇵🇰', name: 'Pakistan', nameAr: 'باكستان', placeholder: '300 1234567' },
  { code: '+51', country: 'PE', flag: '🇵🇪', name: 'Peru', nameAr: 'بيرو', placeholder: '912 345 678' },
  { code: '+63', country: 'PH', flag: '🇵🇭', name: 'Philippines', nameAr: 'الفلبين', placeholder: '917 123 4567' },
  { code: '+48', country: 'PL', flag: '🇵🇱', name: 'Poland', nameAr: 'بولندا', placeholder: '512 345 678' },
  { code: '+351', country: 'PT', flag: '🇵🇹', name: 'Portugal', nameAr: 'البرتغال', placeholder: '912 345 678' },
  { code: '+40', country: 'RO', flag: '🇷🇴', name: 'Romania', nameAr: 'رومانيا', placeholder: '712 345 678' },
  { code: '+7', country: 'RU', flag: '🇷🇺', name: 'Russia', nameAr: 'روسيا', placeholder: '912 345 6789' },
  { code: '+65', country: 'SG', flag: '🇸🇬', name: 'Singapore', nameAr: 'سنغافورة', placeholder: '8123 4567' },
  { code: '+421', country: 'SK', flag: '🇸🇰', name: 'Slovakia', nameAr: 'سلوفاكيا', placeholder: '912 345 678' },
  { code: '+386', country: 'SI', flag: '🇸🇮', name: 'Slovenia', nameAr: 'سلوفينيا', placeholder: '41 123 456' },
  { code: '+27', country: 'ZA', flag: '🇿🇦', name: 'South Africa', nameAr: 'جنوب أفريقيا', placeholder: '71 234 5678' },
  { code: '+34', country: 'ES', flag: '🇪🇸', name: 'Spain', nameAr: 'إسبانيا', placeholder: '612 34 56 78' },
  { code: '+94', country: 'LK', flag: '🇱🇰', name: 'Sri Lanka', nameAr: 'سريلانكا', placeholder: '71 234 5678' },
  { code: '+46', country: 'SE', flag: '🇸🇪', name: 'Sweden', nameAr: 'السويد', placeholder: '70 123 45 67' },
  { code: '+41', country: 'CH', flag: '🇨🇭', name: 'Switzerland', nameAr: 'سويسرا', placeholder: '78 123 45 67' },
  { code: '+66', country: 'TH', flag: '🇹🇭', name: 'Thailand', nameAr: 'تايلاند', placeholder: '81 234 5678' },
  { code: '+380', country: 'UA', flag: '🇺🇦', name: 'Ukraine', nameAr: 'أوكرانيا', placeholder: '50 123 4567' },
  { code: '+598', country: 'UY', flag: '🇺🇾', name: 'Uruguay', nameAr: 'أوروغواي', placeholder: '99 123 456' },
  { code: '+58', country: 'VE', flag: '🇻🇪', name: 'Venezuela', nameAr: 'فنزويلا', placeholder: '412 1234567' },
  { code: '+84', country: 'VN', flag: '🇻🇳', name: 'Vietnam', nameAr: 'فيتنام', placeholder: '91 234 5678' }
];
