export const API_ENDPOINTS = {
  home: `/home`,
  about: `/about`,
  contact: `/contact`,
  solutions: `/solutions`,
  solutionTypes: `/solutions-types`,
  search: `/search`,
  info: `/info`,
  projects: `/projects`,
  projectTypes: `/projects-types`,
  industries: `/industries`,
  blogs: `/blogs`,
  clientsPartner: `/clients-partner`,
  privacyPolicy: `/privacy-policy`,
  requestQuote: `/request-quote`,
} as const;
